spring:
  application:
    name: Demo11_Validation

  datasource:
    url: jdbc:mysql://localhost:3306/demo11_validation?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
