spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dtn_thymeleaf?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        # đặt tên cột sát nhau (k dùng dấu "_")
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: nguyenvantuyen6789@gmail.com
#    password: qifx fobl kbsd ysmw
#    properties:
#      mail:
#        smtp:
#          auth: true
#        starttls:
#          enable: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvantuyen6789@gmail.com
    password: qifx fobl kbsd ysmw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
