spring:
  application:
    name: Demo07_ModelMapper_Mapstruct
  datasource:
    url: jdbc:mysql://localhost:3306/dtn_demo07?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
