spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dtn_security_prod?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none # thay đổi entity cũng k tự động gen db
